name: CI Results
on:
  workflow_run:
    workflows: [CI]
    types: [ completed ]

permissions:
  checks: write

jobs:
  report:
    name: Publish reports
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    if: ${{ always() }}
    steps:
      - name: 'Get PR number for commit'
        id: pr-context
        env:
          GH_TOKEN: ${{ github.token }}
          PR_TARGET_REPO: ${{ github.repository }}
          PR_SHA: ${{ github.event.workflow_run.head_sha }}
        run: |
          gh search prs "${PR_SHA}" --repo "${PR_TARGET_REPO}" --json 'number' \
            --jq '"pr_number=\(.[0].number)"' >> "${GITHUB_OUTPUT}"
      - name: 'Comment on PR'
        if: env.pr_number != null
        env:
          pr_number: ${{ steps.pr-context.outputs.pr_number }}
        run: echo ${{ env.pr_number }}
      - name: Download all workflow run artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}
      - name: Publish Test Report
        uses: ptsd/action-junit-report@feature/allow_ignore_classname_in_resolver2
        if: always()
        with:
          commit: ${{github.event.workflow_run.head_sha}}
          report_paths: '**/*.xml'
          check_name: Nextest Report
          detailed_summary: true
          include_passed: false
          group_suite: true
          annotate_notice: true
          check_annotations: true
          resolve_ignore_classname: true
          comment: true
          issue_number: ${{ steps.pr-context.outputs.pr_number }}