name: Test Avian

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository code.
      uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Install alsalib headers
      run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
    - name: Run tests for repository.
      run: cargo test --no-default-features --features "avian" -- -Z unstable-options --format json --report-time | tee results.json
    - name: Prepare junit report
      id: cargo_reporter
      uses: innoq/action-cargo-test-report@v1
      with:
        cargo-test-report-json: 'results.json'
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@main
      if: always()
      with:
        check_name: Test Report
        fail_on_failure: true
        require_tests: true
        summary: ${{ steps.cargo_reporter.outputs.summary }}